# Dependabot config
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    ignore:
      - dependency-name: "numpy"
        versions: ["1.19.5"]
