name: Build and publish GitHub Pages

# Build on all pushes to master for testing
#on:
# release:
#   types: [released]

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r docsrc/requirements.txt

    - name: Build sphinx
      working-directory: docsrc
      run: make html

    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docsrc/_build/html/
        enable_jekyll: true
